### ISSUE TITLE
Unable to use! App crashing

### ISSUE THREAD

**Issue by abdulghanitech** [RobotPajamas/Stetho-Couchbase#8]
`E/AndroidRuntime: FATAL EXCEPTION: StethoWorker-main-1
    Process: com.volteo.maritime.wayship, PID: 26014
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/couchbase/lite/ManagerOptions;
        at com.robotpajamas.stetho.couchbase.CouchbasePeerManager.<init>(CouchbasePeerManager.java:53)
        at com.robotpajamas.stetho.couchbase.CouchbaseInspectorModulesProvider.get(CouchbaseInspectorModulesProvider.java:35)
        at com.facebook.stetho.Stetho$BuilderBasedInitializer.getInspectorModules(Stetho.java:528)
        at com.facebook.stetho.Stetho$Initializer$RealSocketHandlerFactory.create(Stetho.java:456)
        at com.facebook.stetho.server.LazySocketHandler.getSocketHandler(LazySocketHandler.java:42)
        at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
        at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.couchbase.lite.ManagerOptions" on path: DexPathList[[zip file "/data/app/com.volteo.maritime.wayship-WTukljwk7eTcufBALdycOw==/base.apk"],nativeLibraryDirectories=[/data/app/com.volteo.maritime.wayship-WTukljwk7eTcufBALdycOw==/lib/arm64, /data/app/com.volteo.maritime.wayship-WTukljwk7eTcufBALdycOw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.robotpajamas.stetho.couchbase.CouchbasePeerManager.<init>(CouchbasePeerManager.java:53) 
        at com.robotpajamas.stetho.couchbase.CouchbaseInspectorModulesProvider.get(CouchbaseInspectorModulesProvider.java:35) 
        at com.facebook.stetho.Stetho$BuilderBasedInitializer.getInspectorModules(Stetho.java:528) 
        at com.facebook.stetho.Stetho$Initializer$RealSocketHandlerFactory.create(Stetho.java:456) 
        at com.facebook.stetho.server.LazySocketHandler.getSocketHandler(LazySocketHandler.java:42) 
        at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36) 
        at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167) `

**Comment by sureshjoshi** [comment]
Hi @abdulghani200 I haven't used Couchbase in the past 2-3 years, so I haven't kept this repo updated.

Facebook has updated Stetho, and I'm sure Couchbase has updated too - so I'd be surprised if they still work together. 

I might take a look over the Christmas break, but definitely not in the next couple weeks. I've been meaning to update this library, because I want to use Stetho for some other stuff as well (unrelated to CB).
